# Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel("../Database/spotify_songs_initial.xlsx")

# Data Initial Description

In [3]:
display(df.head(3))

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-2.634,1,0.0583,0.1020,0.000000,0.0653,0.518,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,11,-4.969,1,0.0373,0.0724,0.004210,0.3570,0.693,99.972,162600
2,1z1Hg7Vb0AhHDiEmnDE79l,All the Time - Don Diablo Remix,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-3.432,0,0.0742,0.0794,0.000023,0.1100,0.613,124.008,176616

In [4]:
print(f"Dataset shape: {df.shape}")
print(f"Data Types and Non-Nulls Counts:")
display(df.info())
print("Dataset Summary Statistics (Numerical):")
display(df.describe())
print("Dataset Summary Statistics (Categorial):")
display(df.describe(include = 'object'))

Dataset shape: (32833, 23)
Data Types and Non-Nulls Counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32833 entries, 0 to 32832
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_id                  32833 non-null  object
 1   track_name                32828 non-null  object
 2   track_artist              32828 non-null  object
 3   track_popularity          32833 non-null  int64
 4   track_album_id            32833 non-null  object
 5   track_album_name          32828 non-null  object
 6   track_album_release_date  32833 non-null  object
 7   playlist_name             32833 non-null  object
 8   playlist_id               32833 non-null  object
 9   playlist_genre            32833 non-null  object
 10  playlist_subgenre         32833 non-null  object
 11  danceability              32833 non-null  float64
 12  energy                    32833 non-null  float64
 13  key                       32833 non-null  int64
 14  loudness                  32833 non-null  float64
 15  mode                      32833 non-null  int64
 16  speechiness               32833 non-null  float64
 17  acousticness              32833 non-null  float64
 18  instrumentalness          32833 non-null  float64
 19  liveness                  32833 non-null  float64
 20  valence                   32833 non-null  float64
 21  tempo                     32833 non-null  float64
 22  duration_ms               32833 non-null  int64
dtypes: float64(9), int64(4), object(10)
memory usage: 5.8+ MB

None

Dataset Summary Statistics (Numerical):

,track_popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
count,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000
mean,42.477081,0.654850,0.698619,5.374471,-6.719499,0.565711,0.107068,0.175334,0.084747,0.190176,0.510561,120.881132,225799.811622
std,24.984074,0.145085,0.180910,3.611657,2.988436,0.495671,0.101314,0.219633,0.224230,0.154317,0.233146,26.903624,59834.006182
min,0.000000,0.000000,0.000175,0.000000,-46.448000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4000.000000
25%,24.000000,0.563000,0.581000,2.000000,-8.171000,0.000000,0.041000,0.015100,0.000000,0.092700,0.331000,99.960000,187819.000000
50%,45.000000,0.672000,0.721000,6.000000,-6.166000,1.000000,0.062500,0.080400,0.000016,0.127000,0.512000,121.984000,216000.000000
75%,62.000000,0.761000,0.840000,9.000000,-4.645000,1.000000,0.132000,0.255000,0.004830,0.248000,0.693000,133.918000,253585.000000
max,100.000000,0.983000,1.000000,11.000000,1.275000,1.000000,0.918000,0.994000,0.994000,0.996000,0.991000,239.440000,517810.000000

Dataset Summary Statistics (Categorial):

,track_id,track_name,track_artist,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,playlist_subgenre
count,32833,32828,32828,32833,32828,32833,32833,32833,32833,32833
unique,28356,23449,10692,22545,19743,4530,449,471,6,24
top,7BKLCZ1jbUBVqRi2FVlTVw,Poison,Martin Garrix,5L1xcowSxwzFUSJzvyMp48,Greatest Hits,2020-01-10,Indie Poptimism,4JkkvMpVl4lSioqQjeAL0q,edm,progressive electro house
freq,10,22,161,42,139,270,308,247,6043,1809

# Initial Data Cleaning

## Deleting Null Indecies:

In [5]:
# show me the indecies of the rows with null values:
null_indices = df[df.isnull().any(axis=1)].index

# 5 rows with null values:
display(df[df.index.isin(null_indices)])

# deleting those rows (don't have name, artist, album and they have 0 popularity, so they are not useful for our analysis)
df = df[~df.index.isin(null_indices)]

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
8151,69gRFGOWY9OMpFJgFol1u0,NaN,NaN,0,717UG2du6utFe7CdmpuUe3,NaN,2012-01-05,HIP&HOP,5DyJsJZOpMJh34WvUrQzMV,rap,...,6,-7.635,1,0.1760,0.0410,0.00000,0.1160,0.649,95.999,282707
9282,5cjecvX0CmC9gK0Laf5EMQ,NaN,NaN,0,3luHJEPw434tvNbme3SP8M,NaN,2017-12-01,GANGSTA Rap,5GA8GDo7RQC3JEanT81B3g,rap,...,11,-5.364,0,0.3190,0.0534,0.00000,0.5530,0.191,146.153,202235
9283,5TTzhRSWQS4Yu8xTgAuq6D,NaN,NaN,0,3luHJEPw434tvNbme3SP8M,NaN,2017-12-01,GANGSTA Rap,5GA8GDo7RQC3JEanT81B3g,rap,...,10,-5.907,0,0.3070,0.0963,0.00000,0.0888,0.505,86.839,206465
19568,3VKFip3OdAvv4OfNTgFWeQ,NaN,NaN,0,717UG2du6utFe7CdmpuUe3,NaN,2012-01-05,Reggaeton viejitoð¥,0si5tw70PIgPkY1Eva6V8f,latin,...,11,-6.075,0,0.0366,0.0606,0.00653,0.1030,0.726,97.017,252773
19811,69gRFGOWY9OMpFJgFol1u0,NaN,NaN,0,717UG2du6utFe7CdmpuUe3,NaN,2012-01-05,latin hip hop,3nH8aytdqNeRbcRCg3dw9q,latin,...,6,-7.635,1,0.1760,0.0410,0.00000,0.1160,0.649,95.999,282707

## Handling duplicates
* Duplicates will be determined by "str type" columns.
* Before removing a duplicate, its "numric cols" will be averaged.

In [6]:
dup_cols = [
    'track_name', 
    'track_artist', 
    'track_album_name', 
    'playlist_name', 
    'playlist_genre', 
    'playlist_subgenre'
]

df.sort_values(by = 'track_popularity', ascending=False, inplace=True)

rows = len(df)
df.drop_duplicates(subset=dup_cols, keep='first', inplace=True)

print(f"{rows - len(df)} duplicate rows dropped. {len(df)} rows remaining.")

24 duplicate rows dropped. 32804 rows remaining.

## Removing useless columns
* Irrelevant cols: ['track_id', 'track_name', 'track_album_id', 'playlist_id']

In [7]:
cols_to_drop = ['track_id', 'track_name', 'track_album_id', 'playlist_id']
df.drop(columns=cols_to_drop, inplace=True)

## Basic Fearture Engineering
* **track age**: Extracted and calculated from the original **track_album_release_date** to represent the temporal age of the song, transforming a static date string into a continuous numerical variable.

* **duration_sec**: Converting **duration_ms** into **duration_sec** by splitting it in 1000.

* **One-Hot Encoding (OHE)**: Applied strictly to the low-cardinality playlist_genre feature (dropping the first category to avoid the dummy variable trap). This allows linear models to assign direct, independent weights to the primary genres.
 
* **Cyclical Encoding**: Applied sine and cosine transformations to the key column (pitch classes 0-11). This maps the keys onto a 2D continuous circle, preserving their inherent musical circularity (where key 11 is adjacent to key 0) while avoiding target leakage and the dimensionality bloat of OHE.

### track_age and duration_sec

In [8]:
# calculate the age of the track in years based on the release date:
df['track_release_date'] = pd.to_datetime(df['track_album_release_date'], errors='coerce')
df['track_age'] = (pd.to_datetime('today') - df['track_release_date']).dt.days / 365

# Converting 'duration_ms' into 'duration_sec':
df['duration_sec'] = df['duration_ms'] / 1000

df.drop(columns = ['track_release_date', 'track_album_release_date'], inplace = True)
df.drop(columns = ['duration_ms'], inplace = True)

### OHE ('playlist_genre' column)

In [9]:
# One-Hot Encoding for playlist_genre ---
# Apply OHE with drop_first=True to avoid multicollinearity (Dummy Variable Trap)
df = pd.get_dummies(df, columns=['playlist_genre'], drop_first=True)

genre_cols = [col for col in df.columns if "playlist_genre_" in col]
df[genre_cols] = df[genre_cols].astype('int')

### Cyclical Encoding

In [10]:
# Define the maximum value for the cycle (12 pitch classes, 0 to 11)
max_key = 12

# Create the Sine transformation:
df['key_sin'] = np.sin(2 * np.pi * df['key'] / max_key)
# Create the Cosine transformation:
df['key_cos'] = np.cos(2 * np.pi * df['key'] / max_key)

df.drop(columns = ['key'], inplace = True)

# Exporting Cleaned Dataset

In [12]:
file_path = "../Database/spotify_songs_initial_cleaned.xlsx"
df.to_excel(file_path, index = False)
print(f'Successfully saved cleaned dataset to {file_path}')

Successfully saved cleaned dataset to ../Database/spotify_songs_initial_cleaned.xlsx